import {
  Info,
  Lightbulb,
  TriangleAlert,
  CircleCheck,
  Pencil,
  Rocket,
  Code,
  Code2,
  Layers,
  Github,
  Zap,
  Shield,
  Activity,
  Target,
  Book,
  BookOpen,
  Terminal,
  Settings,
  Database,
  Cloud,
  Lock,
  Key,
  Globe,
  Box,
  Package,
  FileText,
  Folder,
  FolderOpen,
  Link as LinkIcon,
  ArrowRight,
  Star,
  Heart,
  Flag,
  Bell,
  Search,
  Play,
  Wrench,
  Cpu,
  Server,
  GitBranch,
  Sparkles,
  type LucideIcon
} from "lucide-react";

// Maps Mintlify/Lucide icon names (kebab or lowercase) to Lucide components.
const ICONS: Record<string, LucideIcon> = {
  info: Info,
  lightbulb: Lightbulb,
  tip: Lightbulb,
  warning: TriangleAlert,
  "triangle-alert": TriangleAlert,
  "alert-triangle": TriangleAlert,
  check: CircleCheck,
  "circle-check": CircleCheck,
  "check-circle": CircleCheck,
  note: Pencil,
  pencil: Pencil,
  rocket: Rocket,
  code: Code,
  code2: Code2,
  layers: Layers,
  github: Github,
  bolt: Zap,
  zap: Zap,
  shield: Shield,
  activity: Activity,
  target: Target,
  book: Book,
  "book-open": BookOpen,
  terminal: Terminal,
  settings: Settings,
  gear: Settings,
  database: Database,
  cloud: Cloud,
  lock: Lock,
  key: Key,
  globe: Globe,
  box: Box,
  package: Package,
  "file-text": FileText,
  file: FileText,
  folder: Folder,
  "folder-open": FolderOpen,
  link: LinkIcon,
  "arrow-right": ArrowRight,
  star: Star,
  heart: Heart,
  flag: Flag,
  bell: Bell,
  search: Search,
  play: Play,
  wrench: Wrench,
  cpu: Cpu,
  server: Server,
  "git-branch": GitBranch,
  sparkles: Sparkles
};

export function Icon({ icon, size = 18, className }: { icon?: string; size?: number; className?: string }) {
  if (!icon) return null;
  const key = icon.toLowerCase().trim();
  const Cmp = ICONS[key] ?? Box;
  return <Cmp size={size} className={className} aria-hidden />;
}
